version: '3.8'
services:
  db:
    image: postgres:15
    container_name: logimetrics_db
    environment:
      POSTGRES_USER: user_logi
      POSTGRES_PASSWORD: password_logi
      POSTGRES_DB: logimetrics
    ports:
      - "5432:5432"